server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          defaulf-label: config-server
          uri: https://github.com/Black852456/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service