server:
  port: 8080
spring:
  application:
    name: config-service
  cloud:
    config:
      enabled: true
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/Black852456/microservicios-tutorial
          search-paths: config-data
